models/DictionaryCountry.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property string $name
 * @property string $phone_code
 * @property string $phone_mask
 * @property string $phone_placeholder
 *
 * Class DictionaryCountry
 * @package app\models
 */
class DictionaryCountry extends ActiveRecord
{

    /**
     * Static cache for countries
     *
     * @var array
     */
    protected static $countryStaticCache = [];

    /**
     * @return string the name of the table
     */
    public static function tableName()
    {
        return 'dictionary_country';
    }


    /**
     * Find country by name
     *
     * @param $name
     * @param $limit
     * @return DictionaryCountry[]
     */
    public static function findByName($name, $limit = 10)
    {
        $condition = self::find()
            ->where('name LIKE :name || \'%\'', [':name' => mb_strtolower($name)])
            ->limit($limit);

        return $condition->all();
    }


    /**
     * Верент допустимые коды стран
     *
     * @return array
     */
    public function getPhoneCode()
    {
        return [$this->phone_code];
    }


    /**
     * Find country by id with static caching
     *
     * @param $id
     * @return DictionaryCountry|null
     */
    public static function getCountryByIdSC($id)
    {
        if (array_key_exists($id, self::$countryStaticCache)) {
            return self::$countryStaticCache[$id];
        }

        self::$countryStaticCache[$id] = DictionaryCountry::findOne(['id' => (int) $id]);

        return self::$countryStaticCache[$id];
    }

}

models/User.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property int $country_id
 * @property string $name
 * @property string $phone_operator
 * @property string $phone_number
 * @property string $phone_country_code
 *
 * @property DictionaryCountry $country
 *
 * Class User
 * @package app\models
 */
class User extends ActiveRecord
{


    /**
     * @return array
     */
    public function rules()
    {
        return [
            [['name', 'country_id'], 'required'],
            [['name'], 'trim'],

            ['name', 'string', 'length' => [6, 256]],

            ['country_id', 'app\components\validators\CountryValidator'],
        ];
    }


    /**
     * related country
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCountry()
    {
        return $this->hasOne(DictionaryCountry::class, ['id' => 'country_id']);
    }

    /**
     * @return string the name of the table
     */
    public static function tableName()
    {
        return 'user';
    }


    /**
     * Номер телефона пользователя
     *
     * @return string
     */
    public function getPhone()
    {
        return '+'.$this->phone_country_code.'-('.$this->phone_operator.')-'.$this->phone_number;
    }
}

models/UserSearch.php
<?php

namespace app\models;
use yii\data\ActiveDataProvider;

/**
 * Class UserSearch
 * @package app\models
 */
class UserSearch extends User
{

    /**
     * @return array
     */
    public function rules()
    {
        return [
            ['id', 'number'],
            ['name', 'string', 'length' => [2, 256]],
            ['country_id', 'app\components\validators\CountryValidator'],
        ];
    }

    /**
     * Get data provider for render users list
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = User::find()->with('country');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort'=> [
                'defaultOrder' => [
                    'id'=>SORT_DESC
                ]
            ],
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        if (!($this->load($params) && $this->validate())) {
            return $dataProvider;
        }

        if (!empty($this->name)) {
            $query->where('name ILIKE :name || \'%\'', [':name' => $this->name]);
        }

        if (!empty($this->id)) {
            $query->where('id = :id', [':id' => $this->id]);
        }

        return $dataProvider;
    }
}

controllers/CountriesController.php
<?php

namespace app\controllers;

use app\components\helpers\StringHelper;
use app\models\DictionaryCountry;
use Symfony\Component\CssSelector\Parser\Handler\StringHandler;
use yii\filters\ContentNegotiator;
use yii\web\Controller;
use yii\web\Response;

class CountriesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'contentNegotiator' => [
                'class' => ContentNegotiator::className(),
                'formats' => [
                    'application/json' => Response::FORMAT_JSON
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Select countries for autocomplete.
     * @param string $term
     * @return string
     */
    public function actionAutoComplete($term)
    {
        if (is_numeric($term)) {
            $countries = [DictionaryCountry::findOne(['id' => $term])];
        } else {
            $countries = DictionaryCountry::findByName($term);
        }

        $result = [];
        foreach ($countries as $country) {
            $result[] = [
                'id'    => $country->id,
                'label' => StringHelper::ucFirst($country->name),
            ];
        }

        return $result;
    }

}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\forms\UserForm;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\HttpException;

class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays users list.
     *
     * @return string
     */
    public function actionIndex()
    {
        $userSearch = new UserSearch();

        $dataProvider = $userSearch->search(\Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'userSearch'   => $userSearch,
        ]);
    }


    /**
     * Create user action
     *
     * @return string
     * @throws \Exception
     */
    public function actionCreate()
    {
        return $this->_form();
    }


    /**
     * Update users
     *
     * @param null $id
     * @throws \Exception
     * @return string
     */
    public function actionUpdate($id)
    {
        return $this->_form($id);
    }

    /**
     * Edit users form
     *
     * @param $id
     * @return string
     * @throws \Exception
     */
    private function _form($id = null)
    {
        if (!is_null($id)) {
            $formModel = UserForm::loadData($id);
        } else {
            $formModel = new UserForm();
        }

        if (empty($formModel)) {
            throw new HttpException(404, 'User not found');
        }

        $statusSaved = false;
        if ($formModel->load(\Yii::$app->request->post()) && $formModel->validate()) {

            if ($formModel->save()) {
                $statusSaved = true;
                if ($formModel->getIsNewRecord()) {
                    $formModel = new UserForm();
                }
            } else {
                throw new \Exception('ЧТо - то сломалось, попробуйте перезагрузить страницу');
            }

        }

        return $this->render('form', [
            'formModel'   => $formModel,
            'statusSaved' => $statusSaved,
        ]);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => \Yii::t('app', 'ФГУП'),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            [
                'label'   => \Yii::t('app', 'Создать'),
                'url'     => ['/users/create'],
                'options' => [
                    'class' => ''
                ]
            ],
        ],
    ]);
    ?>


    <?
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= \Yii::t('app', 'Федеральное государственное унитарное предприятие «Электронные торги и безопасность»') ?> <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/users/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/users/form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \keygenqt\autocompleteAjax\AutocompleteAjax;

/**
 * @var \app\forms\UserForm $formModel
 * @var bool $statusSaved
 */
?>
<?php $form = ActiveForm::begin(); ?>
    <? if ($statusSaved): ?>
    <div class="alert alert-success" role="alert">
        <? if ($formModel->getIsNewRecord()): ?>
            <?= \Yii::t('app', 'Пользователь успешно внесен в базу') ?>
        <? else: ?>
            <?= \Yii::t('app', 'Пользователь успешно сохранен') ?>
        <? endif ?>
    </div>
    <? endif ?>
<?= $form->field($formModel, 'phone_string') ?>

<?= $form->field($formModel, 'name') ?>

<?= $form->field($formModel, 'country_id')->widget(AutocompleteAjax::class, [
    'multiple' => false,
    'url' => [\yii\helpers\Url::to(['countries/auto-complete'])],
    'options' => ['placeholder' => 'Укажите страну']
]) ?>

    <div class="form-group">
        <?= Html::a('Назад', \yii\helpers\Url::to('/'), ['class' => 'btn btn-default']) ?>
        <?= Html::submitButton(\Yii::t('app', $formModel->getIsNewRecord() ? 'Создать' : 'Сохранить'), ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/users/index.php
<?php

/**
 * @var $this yii\web\View
 * @var $dataProvider \yii\data\ActiveDataProvider
 * @var $userSearch \app\models\UserSearch
 */

$this->title = 'Электронные торги и безопасность';
?>
<div class="site-index">
    <?php
    echo \yii\grid\GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel'  => $userSearch,
        'columns' => [
            [
                'label' => \Yii::t('app', '#'),
                'attribute'  => 'id',
                'class' => 'yii\grid\DataColumn',
                'options' => [
                    'width' => '70px'
                ],
                'value' => function (\app\models\User $data) {
                    return $data->id;
                },
            ],
            [
                'label' => \Yii::t('app', 'ФИО'),
                'attribute'  => 'name',
                'class' => 'yii\grid\DataColumn',
                'value' => function (\app\models\User $data) {
                    return $data->name;
                },
            ],
            [
                'header' => \Yii::t('app', 'Страна'),
                'class' => 'yii\grid\DataColumn',
                'value' => function (\app\models\User $data) {
                    if (!empty($data->country)) {
                        return $data->country->name;
                    } else {
                        return \Yii::t('app', 'Удалена');
                    }
                },
            ],
            [
                'header' => \Yii::t('app', 'Номер телефона'),
                'class' => 'yii\grid\DataColumn',
                'value' => function (\app\models\User $data) {
                    return $data->getPhone();
                },
            ],
            [
                'class'   => 'yii\grid\ActionColumn',
                'buttons' => [
                    'delete' => function () { return ''; },
                    'view' => function () { return ''; },
                ]
            ],
        ],
    ]);

    ?>
</div>